(function(AD_CONFIG, LINKS, RT_CONFIG){
/*! Copyright 2014 Baidu Inc. All Rights Reserved. */
"";
"";
var baidu={version:"1.5.0"};baidu.guid="$BAIDU$";window[baidu.guid]=window[baidu.guid]||{};baidu.sio=baidu.sio||{};baidu.sio._createScriptTag=function(b,a,c){b.setAttribute("type","text/javascript");c&&b.setAttribute("charset",c);b.setAttribute("src",a);document.getElementsByTagName("head")[0].appendChild(b)};baidu.sio._removeScriptTag=function(b){if(b.clearAttributes){b.clearAttributes()}else{for(var a in b){if(b.hasOwnProperty(a)){delete b[a]}}}if(b&&b.parentNode){b.parentNode.removeChild(b)}b=null};baidu.sio.callByBrowser=function(a,g,i){var d=document.createElement("SCRIPT"),e=0,j=i||{},c=j.charset,h=g||function(){},f=j.timeOut||0,b;d.onload=d.onreadystatechange=function(){if(e){return}var k=d.readyState;if("undefined"==typeof k||k=="loaded"||k=="complete"){e=1;try{h();clearTimeout(b)
}finally{d.onload=d.onreadystatechange=null;baidu.sio._removeScriptTag(d)}}};if(f){b=setTimeout(function(){d.onload=d.onreadystatechange=null;baidu.sio._removeScriptTag(d);j.onfailure&&j.onfailure()},f)}baidu.sio._createScriptTag(d,a,c)};baidu.array=baidu.array||{};baidu.each=baidu.array.forEach=baidu.array.each=function(g,e,b){var d,f,c,a=g.length;if("function"==typeof e){for(c=0;c<a;c++){f=g[c];d=e.call(b||g,f,c);if(d===false){break}}}return g};baidu.array.filter=function(h,f,d){var c=[],b=0,a=h.length,g,e;if("function"==typeof f){for(e=0;e<a;e++){g=h[e];if(true===f.call(d||h,g,e)){c[b++]=g}}}return c};;
var f=f||{};f.global=this;f.l=!0;f.n="en";f.m=!0;f.k=function(a){return void 0!==a};f.j=function(a,c,b){a=a.split(".");b=b||f.global;a[0]in b||!b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&f.k(c)?b[d]=c:b=b[d]?b[d]:b[d]={}};f.p=function(a,c,b){f.j(a,c,b)};f.o=function(a,c,b){a[c]=b};f.s=function(){return!1};f.t=function(){};f.r=function(){};function h(a){this.c=a||document}h.prototype.a=null;h.prototype.b=null;function k(a){var c=l;c.a=a;var b=c.c.head||c.c.getElementsByTagName("head")[0]||c.c.body;b.insertBefore(a,b.firstChild);c.a=null}function m(){var a=l;if(a.a)return a.a;if(a.b&&"interactive"===a.b.readyState)return a.b;for(var c=a.c.getElementsByTagName("script"),b=c.length;b--;){var d=c[b];if("interactive"===d.readyState)return a.b=d}return null}var l=new h;var n={},p=[];function r(a,c){function b(){d++;d>=e&&c.apply(null,s(a))}"string"===typeof a&&(a=[a]);for(var d=0,e=a.length,g=0;g<e;g++)t(a[g],b)}function s(a){for(var c=[],b=0;b<a.length;b++)c.push(n[a[b]]||null);return c}
function t(a,c){function b(){var a=d.readyState;if("undefined"===typeof a||/^(?:loaded|complete)$/.test(a))if(a=d.src,d=d.onload=d.onreadystatechange=null,n[a])c(n[a]);else{var b=p.pop();b&&(n[a]=b,c(b))}}if(n[a])c(n[a]);else{var d=u();d.src=a;document.addEventListener?d.onload=b:d.readyState&&(d.onreadystatechange=b);k(d)}}function u(){var a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;return a}
window.ECMA_define=window.ECMA_define||function(a){var c=m();c?(a=a(),(c=c.src)?n[c]=a:p.push(a)):(c=a(),p.push(c))};window.ECMA_require=window.ECMA_require||function(a,c){r(a,c)};"object"!==typeof RT_CONFIG||RT_CONFIG.HOST||(RT_CONFIG.HOST=function(a){return"http://"+a});function v(){this.f={imageplus:[{url:"http://ecma.bdimg.com/public03/imageplus/loader.js"},{url:"http://bs.baidu.com/public03/imageplus/loader-dev.js",mode:"development",cacheTime:1},{url:"http://bs.baidu.com/public03/imageplus/loader-test.js",mode:"test",cacheTime:1}],imageright:[{url:"http://ecma.bdimg.com/public03/imageright/loader.js"},{url:"http://bs.baidu.com/public03/imageright/loader-dev.js",mode:"development"}]};this.d={};var a=location.href.match(/[\?&]ecomMode=([^$&#]+)/);this.h=a?a[1]:
"production"}function w(a,c){var b=baidu.array.filter(c,function(b){return(b.mode||"production")===a.h});if(!b.length)return null;var d=100*Math.random(),e=0,g;baidu.array.each(b,function(a){e+=a.rate?parseInt(a.rate,10):100;if(d<e)return g=a,!1});return g}
function x(a,c,b){var d=c.toLowerCase(),e=a.f[d];if(a.d[d])b&&b(c);else{if(e.length&&(e=w(a,e),!e)){b&&b();return}var g=e?e.url:"",q=e.cacheTime||864E5;g&&(a.d[d]=!0,baidu.sio.callByBrowser(g+"?cache="+Math.ceil(new Date/q),function(){b&&b(c)},{charset:e.charset||"utf-8",onfailure:function(){b&&b()}}))}}v.prototype.load=function(a,c){a="string"===typeof a?a.split(","):a;var b=a.length;if(b){var d=0,e=[],g=function(a){d++;a&&e.push(a);d<b||c&&c(e)},q=this;baidu.array.each(a,function(a){x(q,a,g)})}};
var y=new v,z=["ecom","ma","adLoader"],A=window;z[0]in A||!A.execScript||A.execScript("var "+z[0]);for(var B;z.length&&(B=z.shift());)z.length||void 0===y?A=A[B]?A[B]:A[B]={}:A[B]=y;

})(/** AD_CONFIG */{}, /** LINKS */[], /** RT_CONFIG */{});
//Fri Nov 21 2014 19:36:25 GMT+0800 (CST)